M48
; DRILL file {KiCad 7.0.10} date Fri Feb  9 12:16:26 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-09T12:16:26-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,10,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0453
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.0650
%
G90
G05
T1
X4.819Y-3.247
X5.1537Y-3.247
T2
X2.8642Y-4.0157
T3
X4.871Y-3.2057
X4.871Y-3.497
X4.971Y-3.2057
X4.971Y-3.497
X5.071Y-3.2057
X5.071Y-3.497
T4
X2.8642Y-4.8031
M30
